### ISSUE TITLE
No 'end' event?

### ISSUE THREAD

**Issue by nylen** [dominictarr/split#12]
Does `split` not emit an `end` event when all lines have been processed?

**Comment by dominictarr** [comment]
yes of course it does, but not if your upstream input doesn't.

**Comment by nylen** [comment]
My upstream input is ultimately `through` :) how to get it to emit `end`?

**Comment by dominictarr** [comment]
like this:
```
var stream = through()
stream.end()
//OR
stream.queue(null)
```

**Comment by nylen** [comment]
:+1: thanks!
