### ISSUE TITLE
FYI: "event-stream" dependency is backdoored, apparently starting from v3.3.5

### ISSUE THREAD

**Issue by vladimiry** [dominictarr/split#31]
https://github.com/dominictarr/event-stream/issues/116

Preliminary analysis:
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441749105
- https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759047

**Comment by dominictarr** [comment]
this is all fixed now.
