### ISSUE TITLE
Problem with partitioned unicode characters

### ISSUE THREAD

**Issue by mkronschnabl** [dominictarr/split#5]
We work initially with a tar stream that generates fixed length chunks. This can lead to partitioned unicode characters, e.g.:

```
var buffer, complete, piece1, piece2, pieces, soFar, testBuffer;

testBuffer = new Buffer('テスト試験今日はとても,よい天気で');

piece1 = testBuffer.slice(0, 20);
piece2 = testBuffer.slice(20, testBuffer.length);

// 日 is partitioned
console.log(piece1.toString()); // テスト試験今��
console.log(piece2.toString()); // �はとても,よい天気で
```

And if these chunks are used with the split library they are not fit together properly:

```
soFar = piece1.toString();
buffer = piece2;

pieces = (soFar + buffer).split(/,/g);

// the resulting unicode string is corrupt due to the string concatenation
console.log(pieces); // [ 'テスト試験今���はとても', 'よい天気で' ]
```

At the moment we have no solution for this problem, maybe buffer concatenation can help:

```
complete = Buffer.concat([piece1, piece2]);
console.log(complete.toString()); // テスト試験今日はとても,よい天気で
```

Do you think there is a way to cope with this problem?

**Comment by frosas** [comment]
Should this be closed considering the original issue has already been fixed?
